### ISSUE TITLE
How do I find the lel0_sync_vec64_long offset?

### ISSUE THREAD

**Issue by MajickTek** [MTJailed/PurpleSmoke#2]
I already got the kernel_base for my device and everything else stays empty. but searching google for "lel0_sync_vec64_long" only brings me to your repo, nothing else.

**Comment by thealphawerewolf** [comment]
if possible could u add 11.2.1 offsets for iphone 6

**Comment by Dave1482** [comment]
I've made a pull request to add it to the output, but instead of 0x1234567 it should be more like 0xfffffff001234567

**Comment by ethanpepro** [comment]
If you cannot find that address, I don’t think you should be doing this, there are literally tutorials out there now.

Not to mention anything @MTJailed puts out is a sham.

**Comment by MajickTek** [comment]
Actually, unjailme legit works on iOS 11.3 iPhone 8 I tested it recently.

**Comment by MajickTek** [comment]
Thanks for the link though.

**Comment by MTJailed** [comment]
Offtopic comments are removed and unappreciations as well.

**Comment by MTJailed** [comment]
You don't need IDA at all
to find the offset using my logic all you need to do is to run the project and take account of the kernel textbase in the panic log and the leaked pointer in the output, then you can just add them to the offsets file

**Comment by MajickTek** [comment]
ok thanks your reply is much more helpful.
I will be trying this out soon. This will also help me see if i have the right kernel pointer for my device.
I'll tell you if I have issues.

**Comment by MTJailed** [comment]
Like the article said, anythig that has 25c at the end pretty much means it is the correct one.
